Init partner-integration project
GalaxyFinX/partner-integration pull request #2
Opened 2024-09-30 06:31 UTC by hieu-vu-vikki

2024-10-02 01:50 UTC, nquandev requested changes

2024-10-02 01:50 UTC, nquandev commented on common/src/main/java/com/finx/partner_integration/common/constant/IsoResponseCode.java
> +}
Please remove this file.

2024-10-02 01:50 UTC, nquandev commented on common/src/main/java/com/finx/partner_integration/common/constant/IsoField.java
> +}
Please remove the unused file.

2024-10-02 01:50 UTC, nquandev commented on core/build.gradle
> +    implementation libs.commonLang3
Remove these dependencies

2024-10-06 07:57 UTC, LouGalax commented on common/src/main/java/com/finx/partner_integration/common/constants/DumpConstants.java
> +}
Why named `DumpConstants`

2024-10-06 07:58 UTC, LouGalax commented on core/src/main/java/com/finx/partner_integration/core/configuration/JacksonConfiguration.java
> +  }
`Spring-Boot` already defined an configured `ObjectMapper`. Why not use it ?

2024-10-06 07:59 UTC, LouGalax commented on core/src/main/java/com/finx/partner_integration/core/domain/PartnerIntegrationConfig.java
> +@Builder
should not use `@Builder` . We already use `MapStruct`

2024-10-06 08:02 UTC, LouGalax commented on core/src/main/java/com/finx/partner_integration/core/service/PartnerIntegrationConfigService.java
> +  }
I think throw Exception in here is unlikely. It should be gently ignored, and return the current partner.

2024-10-06 08:02 UTC, LouGalax commented on core/src/main/java/com/finx/partner_integration/core/service/PartnerIntegrationConfigService.java
> +  }
Use `filter` to switch instead of `flatMap`

2024-10-06 08:03 UTC, LouGalax commented on infra/src/main/java/com/finx/partner_integration/infra/filter/RequestAndResponseLogGlobalFilter.java
> +// }
If not used, delete it

2024-10-08 09:53 UTC, nquandev requested changes

2024-10-08 09:53 UTC, nquandev commented on infra/src/main/java/com/finx/partner_integration/infra/LoggingInterceptor.java
> +                  response.bodyToMono(String.class).doOnNext(responseBody::append).block()))
Try to avoid block() in reactor.

2024-10-08 09:53 UTC, nquandev commented on infra/src/main/java/com/finx/partner_integration/infra/shb/client/SHBClientConfiguration.java
> +    return WebClient.builder()
Please support the micrometer in monitoring the endpoint.

2024-10-09 02:24 UTC, hieu-vu-vikki commented on build.gradle
> +        implementation "io.netty:netty-resolver-dns-native-macos:4.1.72.Final:osx-x86_64"
i'll remove it because it is not necessary when we're deploying on higher environment, which is running on Linux OS

2024-10-09 02:26 UTC, hieu-vu-vikki commented on core/src/main/java/com/finx/partner_integration/core/service/PartnerIntegrationConfigService.java
> +  }
i think we should throw the exception to let the users of the api know what the problem

2024-10-09 02:26 UTC, hieu-vu-vikki commented on core/src/main/java/com/finx/partner_integration/core/domain/PartnerIntegrationConfig.java
> +@Builder
agree, i'll remove it

2024-10-09 02:30 UTC, hieu-vu-vikki commented on core/src/main/java/com/finx/partner_integration/core/configuration/JacksonConfiguration.java
> +  }
the ObjectMapper in AutoConfiguration is not enough functionality in our usage.
For example: https://stackoverflow.com/questions/27952472/serialize-deserialize-java-8-java-time-with-jackson-json-mapper
the objectmapper in AutoConfiguration is not supported ZonedDateTime

2024-10-09 02:31 UTC, hieu-vu-vikki commented on common/src/main/java/com/finx/partner_integration/common/constants/DumpConstants.java
> +}
change to => CommonConstants

2024-10-09 08:26 UTC, nquandev commented on core/src/main/java/com/finx/partner_integration/core/service/PartnerIntegrationConfigService.java
> +        .zipWhen(x -> eventPublisher.publishRefreshEvent())
Remove this line.

2024-10-10 02:09 UTC, nguyenduy3101 approved these changes

2024-10-10 02:12 UTC, nguyenduy3101 approved these changes

2024-10-10 02:44 UTC, merged